/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedComoFuncionaRouteImport } from './routes/_authenticated/como-funciona'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedIndicarEmpresaRouteImport } from './routes/_authenticated/indicar-empresa'
import { Route as AuthenticatedIndicarPesquisadorRouteImport } from './routes/_authenticated/indicar-pesquisador'
import { Route as AuthenticatedMinhasBonificacoesRouteImport } from './routes/_authenticated/minhas-bonificacoes'
import { Route as AuthenticatedMinhasIndicacoesRouteImport } from './routes/_authenticated/minhas-indicacoes'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminFinanceiroRouteImport } from './routes/_authenticated/admin.financeiro'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedComoFuncionaRoute =
  AuthenticatedComoFuncionaRouteImport.update({
    id: '/como-funciona',
    path: '/como-funciona',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIndicarEmpresaRoute =
  AuthenticatedIndicarEmpresaRouteImport.update({
    id: '/indicar-empresa',
    path: '/indicar-empresa',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIndicarPesquisadorRoute =
  AuthenticatedIndicarPesquisadorRouteImport.update({
    id: '/indicar-pesquisador',
    path: '/indicar-pesquisador',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMinhasBonificacoesRoute =
  AuthenticatedMinhasBonificacoesRouteImport.update({
    id: '/minhas-bonificacoes',
    path: '/minhas-bonificacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMinhasIndicacoesRoute =
  AuthenticatedMinhasIndicacoesRouteImport.update({
    id: '/minhas-indicacoes',
    path: '/minhas-indicacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminFinanceiroRoute =
  AuthenticatedAdminFinanceiroRouteImport.update({
    id: '/admin/financeiro',
    path: '/admin/financeiro',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/como-funciona': typeof AuthenticatedComoFuncionaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/indicar-empresa': typeof AuthenticatedIndicarEmpresaRoute
  '/indicar-pesquisador': typeof AuthenticatedIndicarPesquisadorRoute
  '/minhas-bonificacoes': typeof AuthenticatedMinhasBonificacoesRoute
  '/minhas-indicacoes': typeof AuthenticatedMinhasIndicacoesRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/como-funciona': typeof AuthenticatedComoFuncionaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/indicar-empresa': typeof AuthenticatedIndicarEmpresaRoute
  '/indicar-pesquisador': typeof AuthenticatedIndicarPesquisadorRoute
  '/minhas-bonificacoes': typeof AuthenticatedMinhasBonificacoesRoute
  '/minhas-indicacoes': typeof AuthenticatedMinhasIndicacoesRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/como-funciona': typeof AuthenticatedComoFuncionaRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/indicar-empresa': typeof AuthenticatedIndicarEmpresaRoute
  '/_authenticated/indicar-pesquisador': typeof AuthenticatedIndicarPesquisadorRoute
  '/_authenticated/minhas-bonificacoes': typeof AuthenticatedMinhasBonificacoesRoute
  '/_authenticated/minhas-indicacoes': typeof AuthenticatedMinhasIndicacoesRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/como-funciona'
    | '/dashboard'
    | '/financeiro'
    | '/indicar-empresa'
    | '/indicar-pesquisador'
    | '/minhas-bonificacoes'
    | '/minhas-indicacoes'
    | '/perfil'
    | '/admin/financeiro'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/como-funciona'
    | '/dashboard'
    | '/financeiro'
    | '/indicar-empresa'
    | '/indicar-pesquisador'
    | '/minhas-bonificacoes'
    | '/minhas-indicacoes'
    | '/perfil'
    | '/admin/financeiro'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/como-funciona'
    | '/_authenticated/dashboard'
    | '/_authenticated/financeiro'
    | '/_authenticated/indicar-empresa'
    | '/_authenticated/indicar-pesquisador'
    | '/_authenticated/minhas-bonificacoes'
    | '/_authenticated/minhas-indicacoes'
    | '/_authenticated/perfil'
    | '/_authenticated/admin/financeiro'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/como-funciona': {
      id: '/_authenticated/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof AuthenticatedComoFuncionaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/indicar-empresa': {
      id: '/_authenticated/indicar-empresa'
      path: '/indicar-empresa'
      fullPath: '/indicar-empresa'
      preLoaderRoute: typeof AuthenticatedIndicarEmpresaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/indicar-pesquisador': {
      id: '/_authenticated/indicar-pesquisador'
      path: '/indicar-pesquisador'
      fullPath: '/indicar-pesquisador'
      preLoaderRoute: typeof AuthenticatedIndicarPesquisadorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/minhas-bonificacoes': {
      id: '/_authenticated/minhas-bonificacoes'
      path: '/minhas-bonificacoes'
      fullPath: '/minhas-bonificacoes'
      preLoaderRoute: typeof AuthenticatedMinhasBonificacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/minhas-indicacoes': {
      id: '/_authenticated/minhas-indicacoes'
      path: '/minhas-indicacoes'
      fullPath: '/minhas-indicacoes'
      preLoaderRoute: typeof AuthenticatedMinhasIndicacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/financeiro': {
      id: '/_authenticated/admin/financeiro'
      path: '/admin/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AuthenticatedAdminFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedComoFuncionaRoute: typeof AuthenticatedComoFuncionaRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedIndicarEmpresaRoute: typeof AuthenticatedIndicarEmpresaRoute
  AuthenticatedIndicarPesquisadorRoute: typeof AuthenticatedIndicarPesquisadorRoute
  AuthenticatedMinhasBonificacoesRoute: typeof AuthenticatedMinhasBonificacoesRoute
  AuthenticatedMinhasIndicacoesRoute: typeof AuthenticatedMinhasIndicacoesRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedAdminFinanceiroRoute: typeof AuthenticatedAdminFinanceiroRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedComoFuncionaRoute: AuthenticatedComoFuncionaRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedIndicarEmpresaRoute: AuthenticatedIndicarEmpresaRoute,
  AuthenticatedIndicarPesquisadorRoute: AuthenticatedIndicarPesquisadorRoute,
  AuthenticatedMinhasBonificacoesRoute: AuthenticatedMinhasBonificacoesRoute,
  AuthenticatedMinhasIndicacoesRoute: AuthenticatedMinhasIndicacoesRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedAdminFinanceiroRoute: AuthenticatedAdminFinanceiroRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
